apiVersion: v1
kind: Service
metadata:
  name: lanche-rapido-svc
spec:
  
  selector:
    app: lanche-rapido
  ports:
    - protocol: TCP
      name: app
      port: 80
      targetPort: 8080
      nodePort: 30007 # Você pode especificar uma porta entre 30000-32767
  type: NodePort
