apiVersion: v1
kind: Service
metadata:
  name: lanche-rapido-load-balancer
spec:
  selector:
    app: lanche-rapido
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
