apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanche-rapido
  labels:
    app: lanche-rapido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanche-rapido
  template:
    metadata:
      labels:
        app: lanche-rapido
    spec:
      containers:
      - name: app
        image: cesarmoroni1/teste:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 40m
            memory: 100Mi
          limits:
            cpu: 60m
            memory: 150Mi  