apiVersion: v1
kind: Service
metadata:
  name: lanche-rapido-svc
spec:
  type: NodePort
  selector:
    app: lanche-rapido
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080