version: "3.4"

services:
  mysqldb:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    container_name: 'container_db'
    ports:
      - 1433:1433
    environment:
      - SQL_DATABASE=lancheRapidoBD
      - SQL_PASSWORD=Pa55w0rd2021
      - SQL_ROOT_PASSWORD=Pa55w0rd2021
    networks:
      - rede
    volumes:
      - ~/sqlserver/data:/var/opt/mssql

  spring-app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      DATASOURCE_URL: Data Source=ms-sql-server;Initial Catalog=LancheRapidoBD;Encrypt=false;User ID=SA;Password=Pa55w0rd2021;Trusted_Connection=False; TrustServerCertificate=True;

      DATASOURCE_USERNAME: SA
      DATASOURCE_PASSWORD: Pa55w0rd2021
    networks:
      - rede
    depends_on:
      - ms-sql-server
    volumes:
      - .m2:/root/.m2
networks:
  rede: