name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  ECR_REGISTRY: public.ecr.aws
  ECR_REPOSITORY: techchallenge2
  EKS_CLUSTER_NAME: module-eks-SkNJI
  AWS_REGION: us-east-1

jobs:
  docker_hub:
    name: Build and Publish Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.docker_user }}
        password: ${{ secrets.docker_senha }}

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: lanche-rapido/src
        file: lanche-rapido/src/Dockerfile
        tags: 'cesarmoroni1/teste:latest'
        push: true

   
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
          version: 'v1.30.2' # default is latest stable
          id: install
    
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

          
    - name: Configurar AWS CLI try
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'

        
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

                     
    - name: Verificar Status do Deploy  parte 1
      run: |
        kubectl get pods
        kubectl get svc
    - name: Deploy to EKS
      run: |
        kubectl apply --validate=false  -f lanche-rapido/manifests/lanche-rapido-deployment.yaml  
        kubectl apply --validate=false  -f lanche-rapido/manifests/lanche-rapido-svc.yaml
        kubectl apply --validate=false  -f lanche-rapido/manifests/lanche-rapido-hpa.yaml
    
    - name: Verificar Status do Deploy
      run: |
        kubectl get pods
        kubectl get svc
