name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  ECR_REGISTRY: public.ecr.aws
  ECR_REPOSITORY: techchallenge2
  EKS_CLUSTER_NAME: module-eks-SkNJI
  AWS_REGION: us-east-1

jobs:
  docker_hub:
    name: Build and Publish Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.docker_user }}
        password: ${{ secrets.docker_senha }}

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: lanche-rapido/src
        file: lanche-rapido/src/Dockerfile
        tags: 'cesarmoroni1/teste:latest'
        push: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
        kubectl apply -f lanche-rapido/manifests/lanche-rapido-deployment.yaml
        kubectl apply -f lanche-rapido/manifests/lanche-rapido-svc.yaml
        kubectl apply -f lanche-rapido/manifests/lanche-rapido-hpa.yaml
    
    - name: Verificar Status do Deploy
      run: |
        kubectl get pods
        kubectl get svc
