name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY: public.ecr.aws/c6y4l3f3/techchallenge2
  EKS_CLUSTER_NAME: module-eks-SkNJI
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      working-directory: ./lanche-rapido/src
      run: dotnet restore

    - name: Build
      working-directory: ./lanche-rapido/src
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory: ./lanche-rapido/src
      run: dotnet test --no-restore --verbosity normal

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: public.ecr.aws/c6y4l3f3       
        IMAGE_TAG: "latest"
      working-directory: ./lanche-rapido/src
      run: |
        docker build -t $ECR_REGISTRY:$IMAGE_TAG -f Dockerfile .
        docker push $ECR_REGISTRY:$IMAGE_TAG
    
    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update kube config
      run: aws eks update-kubeconfig --name module-eks-SkNJI --region us-east-1

    - name: Deploy to EKS
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      working-directory: ./lanche-rapido
      run: |
        sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY:$IMAGE_TAG|g" manifests/lanche-rapido-deployment.yaml
        kubectl apply -f https://raw.githubusercontent.com/BrunoAtaulo/techChallengeG24Fase3-LancheRapido/main/lanche-rapido/manifests/lanche-rapido-deployment.yaml --validate=false
        kubectl apply -f https://raw.githubusercontent.com/BrunoAtaulo/techChallengeG24Fase3-LancheRapido/main/lanche-rapido/manifests/lanche-rapido-svc.yaml --validate=false
        kubectl apply -f https://raw.githubusercontent.com/BrunoAtaulo/techChallengeG24Fase3-LancheRapido/main/lanche-rapido/manifests/lanche-rapido-hpa.yaml --validate=false
        kubectl get pods
        kubectl get svc
